name:                copland-interp
version:             0.1.0.0
github:              "ampetz/copland-interp"
license:             BSD3
author:              "Adam Petz"
maintainer:          "ampetz@ku.edu"
copyright:           "ITTC, University of Kansas"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            some_category

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ampetz/copland-interp#readme>

dependencies:
- base >= 4.7 && < 5
- network
- bytestring
- stm
- containers
- binary
- cryptohash
- nonce
- ed25519
- mtl
- directory
- text
- base64-bytestring
- aeson
- prettyprinter
- optparse-applicative
- QuickCheck

library:
  source-dirs:
  - src
  - extracted_src

#library:
#  source-dird: src/extracted_src

executables:
  copland-interp-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - copland-interp

  server-main-exe:
    main:                ServerMain.hs
    source-dirs:         server_app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - copland-interp

  client-main-exe:
    main:                ClientMain.hs
    source-dirs:         client_app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - copland-interp

  gen-main-exe:
    main:                GenMain.hs
    source-dirs:         gen_app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - copland-interp

tests:
  copland-interp-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - copland-interp